parameters:
- name: version
  type: string
  displayName: Version
- name: derivedFrom
  type: string
  displayName: Derived From Version
  default: latest
- name: skipTests
  type: boolean
  default: false
  displayName: Skip Tests

variables:
  releaseBranch: releases/${{ parameters.version }}

extends:
  template: .azure-pipelines/pipeline.yml
  parameters:
    branch:  ${{ variables.releaseBranch }}
    componentDetection: false
    test: ${{ not(parameters.skipTests) }}
    sign: true
    publishArtifacts: true

    postBuildStages:
    - stage: CreatePR
      jobs:
      ################################################################################
      - job: create_ado_pr
      ################################################################################
        displayName: Create PR in AzureDevOps
        pool:
          vmImage: ubuntu-18.04

        steps:
        - checkout: self

        - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
          - script: git checkout ${{ variables.releaseBranch }}
            displayName: Checkout release branch

        - bash: |
            set -x
            cd release
            npm install
            ls
            node createAdoPr.js ${{ parameters.version }}
          displayName: Create PR in AzureDevOps
          env:
            USER: $(User)
            PAT: $(AdoPAT)
